<table id="tableAsignaturas" class="display compact" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Nivel</th>
                <th>Año</th>
                <th>Carrera</th>
                <th>Universidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Nivel</th>
                <th>Anio</th>
                <th>Carrera</th>
                <th>Universidad</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
    </table>