<table id="tableDepartamentos" class="display compact" width="100%" cellspacing="0">
        <thead>
            <tr>
                 <th>#</th>
                <th>Tipo</th>
                <th>Web</th>
                <th>Encargado</th>
                <th>Telefono</th>
                <th>E-mail</th>
                <th>Campus/Sede</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th>Tipo</th>
                <th>Web</th>
                <th>Encargado</th>
                <th>Telefono</th>
                <th>E-mail</th>
                <th>Campus/Sede</th>
                <th>Acciones</th>
            </tr>
        </tfoot>
        <tbody>
    </table>